# Generated by Django 3.2.5 on 2021-08-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=1000)),
                ('department', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=1500)),
                ('number', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('joined', models.DateField(blank=True)),
            ],
        ),
    ]
